/* eslint-disable */
let data = [
	"United States international university",
	"Kenyatta university",
	"Nairobi university",
	"Riara university",
	"Kenya Methodist",
	"Multimedia university of Kenya",
	"Zetech university",
	"Daystar university",
	"Africa nazarene university",
	"Karatina university",
	"St. Paul’s university",
	"Abia State University",
	"Abubakar Tafawa Balewa University",
	"Achievers University, Owo",
	"Adamawa State University",
	"Adekunle Ajasin University",
	"Adeleke University",
	"Afe Babalola University",
	"African University of Science and Technology",
	"Ahmadu Bello University",
	"Federal University of Technology, Minna",
	"Federal University of Technology, Owerri",
	"Babcock University",
	"American University of Nigeria",
	"Federal University of Technology, Akure",
	"University of Abuja",
	"University of Ibadan",
	"University of Jos",
	"University of Lagos",
	"University of Nigeria",
	"University of Port Harcourt",
	"University of Ilorin",
	"University of Benin",
	"Obafemi Awolowo University",
	"Lagos State University",
	"Ladoke Akintola University of Technology",
	"Bowen University",
	"Bells University of Technology"
]

module.exports = data